pool:
  name: 'MyLocalLaptop'  # Forces it back to your hardware to avoid the Parallelism error

variables:
- group: 'Portfolio-Secrets'
# Using / instead of \ avoids the "Escape Character" error
- name: pythonExe
  value: 'C:/Users/ADMIN/AppData/Local/Programs/Python/Python311/python.exe'

steps:
  - checkout: self
  
  - script: |
      "$(pythonExe)" -m pip install --upgrade pip
      if exist requirements.txt "$(pythonExe)" -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      "$(pythonExe)" monitor_portfolio.py
    env:
      SLACK_TOKEN: $(SLACK_TOKEN)
    displayName: 'Run Portfolio Monitor'